services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
  userdb:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vox
      POSTGRES_PASSWORD: vox
      POSTGRES_DB: vox
    volumes:
      - userdata:/var/lib/postgresql/data

  filedb:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: vox
      POSTGRES_PASSWORD: vox
      POSTGRES_DB: vox
    volumes:
      - filedata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: vox
      RABBITMQ_DEFAULT_PASS: vox
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  userdata:
  filedata:
  rabbitmq:


